add pathPrefix prompt when adding new server
intersystems-community/intersystems-servermanager pull request #175
Opened 2023-03-17 19:09 UTC by yannip1234

This PR fixes add an optional pathPrefix prompt when adding new server.

2023-03-18 01:48 UTC, gjsjohnmurray requested changes
Thanks for the PR. I have suggested a few small changes.

2023-03-18 01:48 UTC, gjsjohnmurray commented on types/index.d.ts
> +	pathPrefix?: string;
I don't think this is correct.

`pathPrefix` is a property of the `webServer` object and is already defined on the `IWebServerSpec` interface above.

2023-03-18 01:48 UTC, gjsjohnmurray commented on src/api/addServer.ts
> +										if (pathPrefix.charAt(0) !== '/') {
```suggestion
										if (pathPrefix.charAt(0) !== "/") {
```
Using doublequotes for consistency.

2023-03-18 01:48 UTC, gjsjohnmurray commented on src/api/addServer.ts
> +											pathPrefix = '/' + pathPrefix;
```suggestion
											pathPrefix = "/" + pathPrefix;
```

2023-03-18 03:05 UTC, yannip1234 commented
Hi John, thanks for catching my error. I've implemented your suggestions!

2023-03-20 10:14 UTC, gjsjohnmurray approved these changes
:+1:

2023-03-20 10:18 UTC, merged